// Types for our data
interface Tool {
  id: number;
  tool_id: string;
  name: string;
  description: string;
  redirect_url: string;
  visits: number | null;
  growth_rate: number | null;
  saves: number;
  category: string;
  cos_logo_url: string | null;
  screenshot: string;
}

// Tools data
export const tools: Tool[] = [
  {
    "id": 180,
    "tool_id": "5959d8f590a74e8a937552b39aa94849",
    "name": "Respond.io",
    "description": "AI Customer conversation management software for capturing and converting leads.",
    "redirect_url": "https://respond.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Advertising Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Respond.io20250407220631.jpg"
  },
  {
    "id": 181,
    "tool_id": "88f069848482a556e416f713d2819905",
    "name": "Ultralytics",
    "description": "AI platform for creating and deploying vision models without coding.",
    "redirect_url": "https://www.ultralytics.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Healthcare",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Ultralytics20250407220715.jpg"
  },
  {
    "id": 182,
    "tool_id": "ffd98066fb9d062229bed295209ec4ee",
    "name": "DeepSeek AI",
    "description": "Provider of advanced AI language models and enterprise solutions.",
    "redirect_url": "https://deepseek.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Large Language Models (LLMs)",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/DeepSeekAI20250407220728.jpg"
  },
  {
    "id": 183,
    "tool_id": "15d2493c6f9bfb2d3188f1316ce6f5b9",
    "name": "Maqnet AI",
    "description": "AI platform for generating creative content and strategies",
    "redirect_url": "https://maqnet.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Content Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MaqnetAI20250407220734.jpg"
  },
  {
    "id": 184,
    "tool_id": "725b21b6ebf917a68fa2730c865c5df8",
    "name": "xMode.ai",
    "description": "xMode.ai is an advanced AI platform tailored towards adult content creators. Offering an array of AI-powered tools, its main function is to transform the content creation process.",
    "redirect_url": "https://xmode.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "NSFW",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/xMode.ai20250407222149.jpg"
  },
  {
    "id": 185,
    "tool_id": "67a44c4ee22b876ba4cb90669a3578c9",
    "name": "Contentful",
    "description": "Digital experience platform for managing personalized content at scale.",
    "redirect_url": "https://www.contentful.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Knowledge Base",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Contentful20250407221813.jpg"
  },
  {
    "id": 186,
    "tool_id": "c85bb6f07c325c8ee4211b5e5944bd1d",
    "name": "LightX",
    "description": "AI tools for photo and video editing with templates.",
    "redirect_url": "https://www.lightxeditor.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Anime & Cartoon Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LightX20250407221842.jpg"
  },
  {
    "id": 187,
    "tool_id": "8ac1d2e1c975c8a6107bf56123f2853c",
    "name": "Law Insider",
    "description": "AI tools for contract drafting, review, and redlining.",
    "redirect_url": "https://www.lawinsider.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Legal Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LawInsider20250407221852.jpg"
  },
  {
    "id": 188,
    "tool_id": "bfa57cb512cce57d0a631506dc0252e9",
    "name": "Builder.io",
    "description": "AI-driven platform for visual development and content management.",
    "redirect_url": "https://www.builder.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Graphic Design",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Builder.io20250407221928.jpg"
  },
  {
    "id": 189,
    "tool_id": "02bafd8d71a34ea331149546ec2da18c",
    "name": "T3 Chat",
    "description": "All-in-one AI chat platform with top models.",
    "redirect_url": "https://t3.chat/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/T3Chat20250407222159.jpg"
  },
  {
    "id": 190,
    "tool_id": "31997a589a292d7796cc4b41cf15e0f1",
    "name": "Triple Whale",
    "description": "AI platform providing unified data and insights for ecommerce.",
    "redirect_url": "https://www.triplewhale.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Advertising Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/TripleWhale20250407222205.jpg"
  },
  {
    "id": 191,
    "tool_id": "7b0403e92639f6d346550311572024f2",
    "name": "miniapps.ai",
    "description": "Create and explore free AI-powered mini apps and chatbots.",
    "redirect_url": "https://miniapps.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/miniapps.ai20250407222228.jpg"
  },
  {
    "id": 192,
    "tool_id": "d171f147d0de658871781f12e17fcb15",
    "name": "Lilys AI",
    "description": "AI tool for summarizing videos, audio, PDFs, and websites.",
    "redirect_url": "https://lilys.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Summarizer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LilysAI20250407222258.jpg"
  },
  {
    "id": 193,
    "tool_id": "2e9406276b8d6766b4935cf74fed033d",
    "name": "Prismic",
    "description": "Headless page builder for fast website content management.",
    "redirect_url": "https://prismic.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Website Designer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Prismic20250407224005.jpg"
  },
  {
    "id": 194,
    "tool_id": "4ddf4cb005260f1c5b21adca4d27c4ab",
    "name": "Jungle",
    "description": "AI flashcards & questions generator for effective studying",
    "redirect_url": "https://jungleai.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI YouTube Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Jungle20250407224017.jpg"
  },
  {
    "id": 195,
    "tool_id": "233ff8a8d4d1e2aab0d05790cb3bfaeb",
    "name": "Websim",
    "description": "Create and share interactive games and web pages easily.",
    "redirect_url": "https://websim.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Landing Page Builder",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Websim20250407224027.jpg"
  },
  {
    "id": 196,
    "tool_id": "fa697ef64a220fd0da7fb2d417f66962",
    "name": "Mathos | AI Math Solver & Calculator",
    "description": "Free AI math solver for students solving complex math problems.",
    "redirect_url": "https://www.mathgptpro.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Homework Helper",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MathosAIMathSolverCalculator20250407224042.jpg"
  },
  {
    "id": 197,
    "tool_id": "eee0a7ea257f8e9aaccfd07ec6a9e656",
    "name": "Dooray!",
    "description": "All-in-one collaboration tool for project management and communication.",
    "redirect_url": "https://gov-dooray.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Task Management",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Dooray20250407224102.jpg"
  },
  {
    "id": 198,
    "tool_id": "fe2298668075dcdb9f6a4c91c79eb56b",
    "name": "Simplify",
    "description": "All-in-one job search platform providing personalized job matches and applications tracking.",
    "redirect_url": "https://simplify.jobs/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Interview Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Simplify20250407224139.jpg"
  },
  {
    "id": 199,
    "tool_id": "51648baa3ec8376ab7ba9d5589a47d8a",
    "name": "OpenPhone",
    "description": "Collaborative phone system for teams and startups.",
    "redirect_url": "https://www.openphone.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/OpenPhone20250407224200.jpg"
  },
  {
    "id": 200,
    "tool_id": "3911679860395595989e2ca7b56a6ac5",
    "name": "Unstuck AI",
    "description": "AI tool for chatting with course materials and gaining insights.",
    "redirect_url": "https://unstuckstudy.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI YouTube Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/UnstuckAI20250407224226.jpg"
  },
  {
    "id": 201,
    "tool_id": "c82dc04b1bffb7e73f4a553be3795507",
    "name": "Maestra",
    "description": "AI-powered transcription and translation in 125+ languages.",
    "redirect_url": "https://maestra.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Podcast Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Maestra20250407224239.jpg"
  },
  {
    "id": 202,
    "tool_id": "251da491d82753ec35f8e25f0c5ed9a5",
    "name": "CharacterHub",
    "description": "Community platform for sharing and developing original characters.",
    "redirect_url": "https://characterhub.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Character",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/CharacterHub20250407224317.jpg"
  },
  {
    "id": 203,
    "tool_id": "3193bf4057e963a2f0603a2d29754db4",
    "name": "Max Studio AI",
    "description": "AI tools for creativity and image enhancement in one platform.",
    "redirect_url": "https://www.maxstudio.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MaxStudioAI20250407224324.jpg"
  },
  {
    "id": 204,
    "tool_id": "15c2b86b97f962935a69bb9e07462769",
    "name": "IconScout",
    "description": "A marketplace for millions of design assets and resources.",
    "redirect_url": "https://iconscout.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI 3D Model Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/IconScout20250407224408.jpg"
  },
  {
    "id": 205,
    "tool_id": "aa0b5fdb82ee595283827601b5541886",
    "name": "Gorgias",
    "description": "Conversational AI platform for ecommerce sales and support automation.",
    "redirect_url": "https://www.gorgias.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Gorgias20250407224444.jpg"
  },
  {
    "id": 206,
    "tool_id": "0593cedb08651d77c3527d84bac5757b",
    "name": "BoldVoice",
    "description": "Accent training app for non-native English speakers.",
    "redirect_url": "https://www.boldvoice.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Reviews Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/BoldVoice20250407224503.jpg"
  },
  {
    "id": 207,
    "tool_id": "6aab6bb2cd13281b7f9c385e228ed70f",
    "name": "Brilliant",
    "description": "Interactive learning platform for math, science, and programming.",
    "redirect_url": "https://brilliant.org/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Course",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Brilliant20250407224553.jpg"
  },
  {
    "id": 208,
    "tool_id": "2c803bcbaa8b74e6ebdc14586831d311",
    "name": "Nume",
    "description": "The AI CFO every founder needs",
    "redirect_url": "https://www.nume.finance/?utm_source=toolify&utm_medium=listing&utm_campaign=waitlist-launch",
    "visits": null,
    "growth_rate": null,
    "saves": 34,
    "category": "AI Accounting Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Nume20250407224611.jpg"
  },
  {
    "id": 209,
    "tool_id": "ca5d99aaeb4111695a7a6dbf101803f4",
    "name": "WUI.AI",
    "description": "AI tool for turning long videos into short clips.",
    "redirect_url": "https://www.wui.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 36,
    "category": "AI Repurpose Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/WUI.AI20250407224621.jpg"
  },
  {
    "id": 210,
    "tool_id": "a44d07ed3822bed79ea04dc085c3f425",
    "name": "LoveStudy",
    "description": "AI tools for creating flashcards, quizzes, and notes for better learning.",
    "redirect_url": "https://lovestudy.ai/?utm_source=toolifyai",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Quizzes",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LoveStudy20250407224649.jpg"
  },
  {
    "id": 211,
    "tool_id": "1b9627d27dcb43a78c8d9987f9f56127",
    "name": "PortfolioGPT",
    "description": "AI-powered tool for generating personalized investment portfolios quickly.",
    "redirect_url": "https://www.portfoliogpt.xyz/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 6,
    "category": "Investing Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/PortfolioGPT20250407224715.jpg"
  },
  {
    "id": 212,
    "tool_id": "d03da642a6be0123712c250006d0270d",
    "name": "Canny",
    "description": "All-in-one customer feedback management platform.",
    "redirect_url": "https://canny.io/features/autopilot?utm_source=toolify&utm_medium=cpc",
    "visits": null,
    "growth_rate": null,
    "saves": 4,
    "category": "Speech-to-Text",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Canny20250407224734.jpg"
  },
  {
    "id": 213,
    "tool_id": "1dcc06e94714892445dd230567547f6e",
    "name": "Themis For Crypto",
    "description": "AI-driven tools for crypto trading and analysis.",
    "redirect_url": "https://themisforcrypto.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 3,
    "category": "AI Trading Bot Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ThemisForCrypto20250407224746.jpg"
  },
  {
    "id": 214,
    "tool_id": "549ab3e85e40a119ce8e4d94e679f163",
    "name": "Windsurf",
    "description": "AI-powered code editor enhancing developer productivity through proactive assistance.",
    "redirect_url": "https://windsurf.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Productivity Tools",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Windsurf20250407224757.jpg"
  },
  {
    "id": 215,
    "tool_id": "1d5ffd3c4e0dde41443505d77bf49d45",
    "name": "Aha",
    "description": "AI platform for influencer marketing with 24/7 support.",
    "redirect_url": "https://www.aha.inc/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Advertising Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Aha20250407224809.jpg"
  },
  {
    "id": 216,
    "tool_id": "aac59a93ed3bec07cbece7382024879c",
    "name": "Agnaistic",
    "description": "Platform for character management and chat interactions.",
    "redirect_url": "https://agnai.chat/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Agnaistic20250407224832.jpg"
  },
  {
    "id": 217,
    "tool_id": "1d203d190fcdf45e40ef7f22692aa650",
    "name": "Leadpages",
    "description": "Landing page builder for high-converting lead generation.",
    "redirect_url": "https://www.leadpages.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "No-Code&Low-Code",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Leadpages20250407224900.jpg"
  },
  {
    "id": 218,
    "tool_id": "164c278654487f68fb67f51d20fa21f6",
    "name": "xoul ai",
    "description": "Platform for creating human-like AI social agents.",
    "redirect_url": "https://xoul.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/xoulai20250407224931.jpg"
  },
  {
    "id": 219,
    "tool_id": "8253e356d14a74a231d074b2c42aeb47",
    "name": "CHAI APP",
    "description": "Leading AI platform for conversational generative AI research.",
    "redirect_url": "https://chai-research.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/CHAIAPP20250407224940.jpg"
  },
  {
    "id": 220,
    "tool_id": "aecd6e510116c1ea454436bd88492442",
    "name": "VidMage AI",
    "description": "AI tool for easy face swapping in media.",
    "redirect_url": "https://vidmage.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "Fun Tools",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/VidMageAI20250407224948.jpg"
  },
  {
    "id": 221,
    "tool_id": "04d751b46263a401eba94143b771321c",
    "name": "Kagi Search",
    "description": "A premium search engine focused on privacy and user experience.",
    "redirect_url": "https://kagi.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/KagiSearch20250407224954.jpg"
  },
  {
    "id": 222,
    "tool_id": "27a706e93eee5f70ecc195df3a4d9603",
    "name": "Thomson Reuters",
    "description": "Global leader in information and technology solutions for professionals.",
    "redirect_url": "https://www.thomsonreuters.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "Legal Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ThomsonReuters20250407225048.jpg"
  },
  {
    "id": 223,
    "tool_id": "ddc7c1837462ae07375607b81cd1fe86",
    "name": "Ghibli AI Generator",
    "description": "Transform photos into Studio Ghibli-style artwork with AI.",
    "redirect_url": "https://ghibliaigenerator.app/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/GhibliAIGenerator20250407225130.jpg"
  },
  {
    "id": 224,
    "tool_id": "e02000ba11b603dbf991cb3138df2a44",
    "name": "Deepsite",
    "description": "AI website generator for code-free web development.",
    "redirect_url": "https://deepsite.site/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "AI SEO Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Deepsite20250407225141.jpg"
  },
  {
    "id": 225,
    "tool_id": "e3b667e6c9188712c0d817119f825eb2",
    "name": "Preemedia - AI UGC Ads",
    "description": "Create Winning Ads with AI Actors",
    "redirect_url": "https://preemedia.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI UGC Video Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Preemedia-AIUGCAds20250407225201.jpg"
  },
  {
    "id": 226,
    "tool_id": "e143c188d303d69015de6638915d9203",
    "name": "AI Coloring Pages Generator Free Online - aiausmalbilder",
    "description": "Creates unique coloring pages from text and images with AI.",
    "redirect_url": "https://www.aiausmalbilder.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/AIColoringPagesGeneratorFreeOnline-aiausmalbilder20250407225217.jpg"
  },
  {
    "id": 227,
    "tool_id": "dd74abc22c96d10e1b04ec1e7188cc1f",
    "name": "Inker.AI",
    "description": "AI tattoo generator for personalized designs from text or images.",
    "redirect_url": "https://www.inker.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Inker.AI20250407225232.jpg"
  },
  {
    "id": 228,
    "tool_id": "50344eba9063c9b79a32acf0ecfb7049",
    "name": "Metric Converter",
    "description": "Free tool for converting multiple unit measurements.",
    "redirect_url": "https://www.metric-converter.com/en?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Other",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MetricConverter20250407225246.jpg"
  },
  {
    "id": 229,
    "tool_id": "5fd5f50f566a7664dd839a8d7c96a5ed",
    "name": "Kie.ai: Affordable and Reliable 4o Image API(The latest released)",
    "description": "Generate styled images with perfect text rendering and character consistency using Kie.ai's affordable 4o Image API.",
    "redirect_url": "https://kie.ai/4o-image-api?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Text to Image",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Kie.aiAffordableandReliable4oImageAPIThelatestreleased20250407225318.jpg"
  },
  {
    "id": 230,
    "tool_id": "61445ce4cd9b93992537f2e04a013679",
    "name": "JoyPix.ai",
    "description": "No-Camera Video Magic with JoyPix.ai! Turn yourself into an anime avatar and make perfect lip-sync videos - no filming required!",
    "redirect_url": "https://www.joypix.ai/?invitation_code=toolify.ai&utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Profile Picture Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/JoyPix.ai20250407225333.jpg"
  },
  {
    "id": 231,
    "tool_id": "ee63b485598c1b5ff8697ea71e0ba8b9",
    "name": "Flowpost.io",
    "description": "Generate Linkedin Carousels and Posts in seconds",
    "redirect_url": "https://flowpost.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Content Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Flowpost.io20250407225353.jpg"
  },
  {
    "id": 232,
    "tool_id": "0bd108a7a2eebba7634fa6e0a6983d98",
    "name": "Ghiblio Art",
    "description": "Free Ghibli Style Image Generator",
    "redirect_url": "https://ghiblio.art/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 5,
    "category": "Text to Image",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/GhiblioArt20250407225403.jpg"
  },
  {
    "id": 233,
    "tool_id": "4dcb5735ef7ac1cdab0635a81d6570a0",
    "name": "Ledger",
    "description": "Meet the all-in-one project management tool that helps teams get more work done, without tedious check-ins, file searching or app-switching.",
    "redirect_url": "https://www.ledgerteams.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Team Collaboration",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Ledger20250407225427.jpg"
  },
  {
    "id": 234,
    "tool_id": "b75e16ad4d7a20bca5d415d607718822",
    "name": "Ghibli Style Image Transformer",
    "description": "AI tool for transforming images into Ghibli-style art",
    "redirect_url": "https://ghiblistyle.net/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/GhibliStyleImageTransformer20250407225434.jpg"
  },
  {
    "id": 235,
    "tool_id": "dc69fb9a6a29d5aea127129177abbdb9",
    "name": "Chargeblast AI",
    "description": "A platform to reduce chargeback rates for startups.",
    "redirect_url": "https://www.chargeblast.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ChargeblastAI20250407225456.jpg"
  },
  {
    "id": 236,
    "tool_id": "b3658b0f8ea9e25a54fff1a261eb573f",
    "name": "Image Upscaler",
    "description": "Image Upscaler provides a wide range of online AI tools for photo and video editing. Beginning as a deep learning convolutional neural network for image upscaling, it since evolved into an AI based multi-tool in image processing, while still providing one of the best image upscaler services.",
    "redirect_url": "https://imageupscaler.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 2,
    "category": "AI Photo & Image Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ImageUpscaler20250407225518.jpg"
  },
  {
    "id": 237,
    "tool_id": "f8aef0618fa963e69431f7c3ab184ebe",
    "name": "SMAAS Platform",
    "description": "AI marketing tool for managing content and sales funnels.",
    "redirect_url": "https://smmaas.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Landing Page Builder",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/SMAASPlatform20250407225525.jpg"
  },
  {
    "id": 238,
    "tool_id": "f228288492a0bbe6f2231ed3134a63db",
    "name": "AUTO PR",
    "description": "AI tool for generating GitHub pull request descriptions.",
    "redirect_url": "https://pr.m3labs.in/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Content Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/AUTOPR20250407230003.jpg"
  },
  {
    "id": 239,
    "tool_id": "4e3a76d2e717908726a1846aef3965f9",
    "name": "Webfuse",
    "description": "A platform for modifying web apps without coding.",
    "redirect_url": "https://www.webfuse.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "No-Code&Low-Code",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Webfuse20250407230012.jpg"
  },
  {
    "id": 240,
    "tool_id": "17afafe494971cc05fde12f93d3e65a9",
    "name": "BloomNote",
    "description": "An AI tool for efficient and personalized learning.",
    "redirect_url": "https://www.bloomnote.me/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Tutorial",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/BloomNote20250407230027.jpg"
  },
  {
    "id": 241,
    "tool_id": "7de7890cf20ea848a930fdee970b9e89",
    "name": "Olivia AI",
    "description": "A multi-model AI assistant for personalized interactions.",
    "redirect_url": "https://play.google.com/store/apps/details?id=com.razor.deepchat&utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/OliviaAI20250407230034.jpg"
  },
  {
    "id": 242,
    "tool_id": "bb1901f9d25ac873af050b13e4b80f9a",
    "name": "Soul Machines",
    "description": "Founded in 2016, Soul Machines is a global pioneer in the humanization of AI. Our patented, ground-breaking Experiential AI™ technology powers emotionally intelligent AI Assistants that create personalized, interactive digital engagement in real time.",
    "redirect_url": "https://www.soulmachines.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 7,
    "category": "AI Avatar Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/SoulMachines20250407230053.jpg"
  } 
];

// Note: For brevity in this response, I'm showing the first and last entries.
// The actual file contains ALL tools from the JSON data with their complete information.