// Types for our data
export interface Tool {
  id: number;
  tool_id: string;
  name: string;
  description: string;
  redirect_url: string;
  visits: number | null;
  growth_rate: number | null;
  saves: number;
  category: string;
  cos_logo_url: string | null;
  screenshot: string;
}

// Tools data
export const tools: Tool[] = [
  {
    "id": 125,
    "tool_id": "5da459e5da005787b9d7c91aa0e7a8a9",
    "name": "Stackie.AI (Notes, Tracker, Memo & More)",
    "description": "💯Best logger + generator app with auto-organizing & auto-completion! Stackie proactively logs & thinks for you with unlimited templates and generative AI - turning ramblings into organized, finished tasks: notes, trackers, memos, lists, briefs, highlights & everything. Input into insight instantly.  From Random Dumps to Ready-to-Use Brilliance.",
    "redirect_url": "https://stackie.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 10,
    "category": "AI Productivity Tools",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Stackie.AINotesTrackerMemoMore20250407214940.jpg"
  },
  {
    "id": 126,
    "tool_id": "148210f382320907c982b44f3f5e47d2",
    "name": "Raena AI",
    "description": "Transform study notes into interactive and engaging learning tools.",
    "redirect_url": "https://raena.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Podcast Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/RaenaAI20250407215009.jpg"
  },
  {
    "id": 127,
    "tool_id": "e51aa668fe01ecefea71f6de88ed16fb",
    "name": "Nim",
    "description": "All-in-one app for AI video production and generation.",
    "redirect_url": "https://nim.video/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Nim20250407215016.jpg"
  },
  {
    "id": 128,
    "tool_id": "902970ad35f67070d4a8d72f018856a5",
    "name": "Miro",
    "description": "Summary: Miro helps distributed teams collaborate and co-create efficiently across different locations.",
    "redirect_url": "https://miro.com/ai?red=toolifc2273c&utm_source=toolifc2273c&utm_medium=cpa&utm_affiliate_network=reditus",
    "visits": null,
    "growth_rate": null,
    "saves": 33,
    "category": "AI Team Collaboration",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Miro20250407215058.jpg"
  },
  {
    "id": 129,
    "tool_id": "64a0c52d8d432dbdb8f1cd95eaa34deb",
    "name": "Relevance AI",
    "description": "Platform for creating and managing an AI workforce.",
    "redirect_url": "https://relevanceai.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/RelevanceAI20250407215136.jpg"
  },
  {
    "id": 130,
    "tool_id": "550bcf5116c2b40bb49ffa9b4cb7b94b",
    "name": "LLMule",
    "description": "Decentralized AI ecosystem for local and P2P model running.",
    "redirect_url": "https://llmule.xyz/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Large Language Models (LLMs)",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LLMule20250407215157.jpg"
  },
  {
    "id": 131,
    "tool_id": "ca3090aae751182693cd55d6cfd4caf9",
    "name": "AI-Powered TailwindCSS Code Generator",
    "description": "AI tool for generating TailwindCSS code from text prompts.",
    "redirect_url": "https://tailwindgenai.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Prompt",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/AI-PoweredTailwindCSSCodeGenerator20250407215214.jpg"
  },
  {
    "id": 132,
    "tool_id": "9e896f45b0e96ff79acb2be2db12e24e",
    "name": "Newt",
    "description": "A comprehensive platform for reading, writing, and listening to stories.",
    "redirect_url": "https://newt.ar/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Story Writing",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Newt20250407215247.jpg"
  },
  {
    "id": 133,
    "tool_id": "eebb0c89c275a50e2c23d529165ebce8",
    "name": "Vidbyte",
    "description": "AI-generated video explanations for learning complex topics.",
    "redirect_url": "https://vidbyte.pro/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Homework Helper",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Vidbyte20250407215259.jpg"
  },
  {
    "id": 134,
    "tool_id": "4e98d4887aee91883ae8fc34f4cd040d",
    "name": "Qaprix Intelligence",
    "description": "AI chatbot solutions for improving business communication and customer support.",
    "redirect_url": "https://qaprix.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/QaprixIntelligence20250407215309.jpg"
  },
  {
    "id": 135,
    "tool_id": "c1801e938ff94be6c303abdb20936c68",
    "name": "Ogilvy",
    "description": "AI text editor for enhanced writing and analytics",
    "redirect_url": "https://ogilvyapp.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Advertising Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Ogilvy20250407215331.jpg"
  },
  {
    "id": 136,
    "tool_id": "8cfe6ef74a77f98e1e695e4309413c69",
    "name": "Stack Studio",
    "description": "AI tool for generating software architecture and technical documentation.",
    "redirect_url": "https://stackstudio.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Code Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/StackStudio20250407215343.jpg"
  },
  {
    "id": 137,
    "tool_id": "76dd78355fc4945750395edadb6e2a8f",
    "name": "Welle",
    "description": "AI investment agent offering personalized insights and real-time data.",
    "redirect_url": "https://welle.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Investing Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Welle20250407215351.jpg"
  },
  {
    "id": 138,
    "tool_id": "c73d2584a8ca3157a0823a4f2182f0e5",
    "name": "Itzam",
    "description": "AI integration tool for seamless application enhancements.",
    "redirect_url": "https://itz.am/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Prompt",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Itzam20250407215358.jpg"
  },
  {
    "id": 139,
    "tool_id": "6b7909eaba489fa463a72d5b11421452",
    "name": "SalesAPE AI",
    "description": "SalesAPE is your AI inbound sales rep - qualifying leads, booking meetings, and growing your revenue 24/7. Built for small businesses. No code, no software setup, no hassle.",
    "redirect_url": "https://www.salesape.ai/?red=toolif4e9d90&utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI API Design",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/SalesAPEAI20250407215412.jpg"
  },
  {
    "id": 140,
    "tool_id": "c8109cd03a56a68836977b352fdc045e",
    "name": "LLM API Costs Widget",
    "description": "App for managing OpenAI API expenses effectively.",
    "redirect_url": "https://apps.apple.com/es/app/llm-api-costs-widget/id6743623133?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Large Language Models (LLMs)",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LLMAPICostsWidget20250407215439.jpg"
  },
  {
    "id": 141,
    "tool_id": "ab92eebff088050496259db0e94ecc7a",
    "name": "Greetigo",
    "description": "AI reminders for important dates with personalized greetings.",
    "redirect_url": "https://greetigo.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Productivity Tools",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Greetigo20250407215448.jpg"
  },
  {
    "id": 142,
    "tool_id": "2d3115d19518672d041af338289fc4b3",
    "name": "Hivescout",
    "description": "AI tool for community engagement and audience connection.",
    "redirect_url": "https://hivescout.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Response Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Hivescout20250407215459.jpg"
  },
  {
    "id": 143,
    "tool_id": "c9ccd45f64e9753ad7b1cdf7bc207e73",
    "name": "Glitch",
    "description": "A community platform for building and sharing web apps.",
    "redirect_url": "https://glitch.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Website Designer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Glitch20250407215512.jpg"
  },
  {
    "id": 144,
    "tool_id": "d18f4157ddc2b10796efec87a11e2f33",
    "name": "PDF Converter",
    "description": "Online tool for converting and editing PDF files.",
    "redirect_url": "https://pdf-converter.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 5,
    "category": "AI PDF",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/PDFConverter20250407215532.jpg"
  },
  {
    "id": 145,
    "tool_id": "f4857e3547135727eba8f8bd965215b5",
    "name": "saasLink",
    "description": "AI tool for generating LinkedIn posts for SaaS companies",
    "redirect_url": "https://saaslink.pro/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Social Media Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/saasLink20250407215542.jpg"
  },
  {
    "id": 146,
    "tool_id": "c024c24a1bdac86abd9aff2446b0aece",
    "name": "AI Equalizer : Music Enhancer",
    "description": "Ultimate audio control and sound enhancement app for Android.",
    "redirect_url": "https://play.google.com/store/apps/details?id=com.arshilgenius.aiequilizer&utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Image Enhancer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/AIEqualizerMusicEnhancer20250407215553.jpg"
  },
  {
    "id": 147,
    "tool_id": "10773d787ffa551c5ec8682650eaba3a",
    "name": "AI Snap&Sort",
    "description": "An app that helps identify right waste disposal methods.",
    "redirect_url": "https://apps.apple.com/ca/app/ai-snap-sort/id6744167034?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Image Scanning",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/AISnapSort20250407215614.jpg"
  },
  {
    "id": 148,
    "tool_id": "e6e976966575c3000c2c1bac538525cd",
    "name": "Rubii AI",
    "description": "Rubii: AI native fandom character UGC platform. Create your character, feed, and stage. Create interactive stories, chat with virtual partners, and explore user-generated content.",
    "redirect_url": "https://rubii.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 45,
    "category": "AI Character",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/RubiiAI20250407215622.jpg"
  },
  {
    "id": 149,
    "tool_id": "e767ca6a64b4aecb8afd36bf39c8ffc9",
    "name": "Buildzero",
    "description": "AI-powered startup idea validation through voice calls.",
    "redirect_url": "https://buildzero.club/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Recruiting",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Buildzero20250407215638.jpg"
  },
  {
    "id": 150,
    "tool_id": "54d3081b260c92461c3c4c13653c0989",
    "name": "G-mate",
    "description": "AI platform for brand promotion and social media management.",
    "redirect_url": "https://www.echomemo.vip/en?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Advertising Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/G-mate20250407215713.jpg"
  },
  {
    "id": 151,
    "tool_id": "5c337e77b389b74b35e9aa8746caaa4c",
    "name": "VRSE - AI Bible Verse Songs",
    "description": "Transform Bible verses into personalized AI-generated songs for memorization.",
    "redirect_url": "https://apps.apple.com/us/app/vrse-ai-bible-verse-songs/id6742088613?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Religion",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/VRSE-AIBibleVerseSongs20250407215735.jpg"
  },
  {
    "id": 152,
    "tool_id": "3af6f8e4388badcf8e0f2f81b72f5dbf",
    "name": "StartupMate",
    "description": "AI platform for validating startup ideas and market insights.",
    "redirect_url": "https://startupmate.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Business Ideas Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/StartupMate20250407215750.jpg"
  },
  {
    "id": 153,
    "tool_id": "879ede75249f02357dae1c30ddbb9c5e",
    "name": "ProgressMade.ai",
    "description": "AI platform for achieving health goals through personalized routines.",
    "redirect_url": "https://progressmade.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Fitness",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ProgressMade.ai20250407215810.jpg"
  },
  {
    "id": 154,
    "tool_id": "3e736f747de809039bfbfdb1b3d8ddc0",
    "name": "Thumb Zone",
    "description": "AI platform for faster, cheaper mobile usability testing.",
    "redirect_url": "https://thumbzone.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Summarizer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ThumbZone20250407215830.jpg"
  },
  {
    "id": 155,
    "tool_id": "f9f7a35ada73be349da2f5f025f34f37",
    "name": "LLM Tester",
    "description": "Cloud-based platform for testing AI chatbots and language models.",
    "redirect_url": "https://llm-tester.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/LLMTester20250407215840.jpg"
  },
  {
    "id": 156,
    "tool_id": "9e164f40d82c8ae901e6481ed6767911",
    "name": "ReInterview",
    "description": "AI mock interviews aiding interview preparation and confidence.",
    "redirect_url": "https://reinterview.co/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Interview Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ReInterview20250407215902.jpg"
  },
  {
    "id": 157,
    "tool_id": "97fdd826b0039d8273fb1914d2f1c603",
    "name": "Catzy",
    "description": "AI app for identifying cat breeds and enhancing photos.",
    "redirect_url": "https://apps.apple.com/in/app/cat-identifier-scanner-catzy/id6743759800?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Image Recognition",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Catzy20250407215922.jpg"
  },
  {
    "id": 158,
    "tool_id": "28f74821b59d9f1cb6cb13ad749bbab9",
    "name": "Brainstorms",
    "description": "Mind mapping tool for visual thinking and idea organization",
    "redirect_url": "https://brainstorms.app/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Mind Mapping",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Brainstorms20250407215934.jpg"
  },
  {
    "id": 159,
    "tool_id": "d97a6cf6c1c362c1d4be3c3c3fa96bd2",
    "name": "Formcraft",
    "description": "AI form builder for quick and sophisticated form creation.",
    "redirect_url": "https://www.formcraft.cloud/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Healthcare",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Formcraft20250407215945.jpg"
  },
  {
    "id": 160,
    "tool_id": "c75cbba6b95f6fcb3483800a62f1edc6",
    "name": "MarkFlow: AI Format Engine",
    "description": "Convert Markdown to multiple formats effortlessly with MarkFlow.",
    "redirect_url": "https://apps.apple.com/us/app/markflow-ai-format-engine/id6743826237?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Presentation Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MarkFlowAIFormatEngine20250407220000.jpg"
  },
  {
    "id": 161,
    "tool_id": "6147fe585e0724b6ce8a15b836d3bb9f",
    "name": "ResumeInvent",
    "description": "ATS resume builder for hassle-free, optimized resumes.",
    "redirect_url": "https://resumeinvent.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Resume Builder",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ResumeInvent20250407220008.jpg"
  },
  {
    "id": 162,
    "tool_id": "984d231a83334ac075cd8010970038d4",
    "name": "Lexence",
    "description": "AI-powered legal assistant for streamlined understanding and drafting of legal content.",
    "redirect_url": "https://www.lexence.tech/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Legal Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Lexence20250407220019.jpg"
  },
  {
    "id": 163,
    "tool_id": "aae43fc7c0e94e6fe1e870abb4d3e620",
    "name": "Teammates.ai",
    "description": "Autonomous AI Teammates that take on entire business functions, end-to-end.",
    "redirect_url": "https://www.teammates.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Blog Writer",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Teammates.ai20250407220036.jpg"
  },
  {
    "id": 164,
    "tool_id": "b580111275376c6bb38637c388d97d72",
    "name": "StudentsGPT",
    "description": "AI companion for academic research and content creation.",
    "redirect_url": "https://www.studentsgpt.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Plagiarism Checker",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/StudentsGPT20250407220045.jpg"
  },
  {
    "id": 165,
    "tool_id": "58a5193520a7f9cea68becd7ee6e256f",
    "name": "Context Garden",
    "description": "A platform to save and discover ChatGPT prompts easily.",
    "redirect_url": "https://context.garden/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Prompt",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ContextGarden20250407220052.jpg"
  },
  {
    "id": 166,
    "tool_id": "0ce685c1ee83f59001e4b7eebc7a2932",
    "name": "Side Reader",
    "description": "Chrome extension for reading and chatting with PDFs effortlessly.",
    "redirect_url": "https://www.side-reader.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/SideReader20250407220101.jpg"
  },
  {
    "id": 167,
    "tool_id": "4290dee4e6058e94020df71582c032c9",
    "name": "UnbiasedAI",
    "description": "AI tool for analyzing media biases and credibility.",
    "redirect_url": "https://unbiasedai.tech/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Detector",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/UnbiasedAI20250407220118.jpg"
  },
  {
    "id": 168,
    "tool_id": "8d85117a8120e472627523a5fd55528b",
    "name": "ScoreGenius",
    "description": "AI tool for accurate football match betting predictions.",
    "redirect_url": "https://scoregenius.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Sports",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/ScoreGenius20250407220144.jpg"
  },
  {
    "id": 169,
    "tool_id": "b8c67466f018cf1d292651a0cecd9972",
    "name": "BlurBackground AI",
    "description": "",
    "redirect_url": "https://blurbackground.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Background Remover",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/BlurBackgroundAI20250407220211.jpg"
  },
  {
    "id": 170,
    "tool_id": "b808eccb6be2bfaec4f05d5ac9c8cfd4",
    "name": "CloudKeeper Tuner",
    "description": "CloudKeeper Tuner -  An Automated AWS Usage Optimization & Recommendation Platform",
    "redirect_url": "https://www.cloudkeeper.com/cloudkeeper-tuner?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI DevOps Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/CloudKeeperTuner20250407220236.jpg"
  },
  {
    "id": 171,
    "tool_id": "ef06ddcc46040c5a9a19a71ba464ebc6",
    "name": "Reditus",
    "description": "Create Word Of Mouth around your B2B SaaS via affiliates and your users.",
    "redirect_url": "https://www.getreditus.com/referral/?red=reditus&sid=toolify&utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "Sales Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/Reditus20250407220244.jpg"
  },
  {
    "id": 172,
    "tool_id": "8dda583d8e24984a46847e6db7262f63",
    "name": "Firecrawl Dev",
    "description": "Extract web data for AI applications efficiently.",
    "redirect_url": "https://www.firecrawl.dev/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Document Extraction",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/FirecrawlDev20250407220254.jpg"
  },
  {
    "id": 173,
    "tool_id": "b3da2220fb339d813d0910b62bdd501f",
    "name": "Hemingway Editor",
    "description": "A tool for improving writing clarity and correctness.",
    "redirect_url": "https://hemingwayapp.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Grammar Checker",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/HemingwayEditor20250407220302.jpg"
  },
  {
    "id": 174,
    "tool_id": "203daa995fa34256f765552b523fccaf",
    "name": "Browser Use",
    "description": "AI-controlled browser automation for web accessibility.",
    "redirect_url": "https://browser-use.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Document Extraction",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/BrowserUse20250407220309.jpg"
  },          
  {
    "id": 175,
    "tool_id": "b670629695f1f16fd6b5b70f458ecc59",
    "name": "MiniMax",
    "description": "Co-creating intelligence through AI applications and APIs",
    "redirect_url": "https://www.minimaxi.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Chatbot",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/MiniMax20250407220326.jpg"
  },
  {
    "id": 176,
    "tool_id": "7de3c01c26f0b98c7a32fbadae14b438",
    "name": "CodeSignal",
    "description": "AI-driven platform for hiring and skills development in tech and business.",
    "redirect_url": "https://codesignal.com/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "AI Interview Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/CodeSignal20250407220354.jpg"
  },
  {
    "id": 177,
    "tool_id": "6ae28edc9ee8d1671f26024512a3669e",
    "name": "The Rundown AI",
    "description": "Daily AI news and insights for professionals.",
    "redirect_url": "https://www.therundown.ai/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 0,
    "category": "Newsletter",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/TheRundownAI20250407220408.jpg"
  },
  {
    "id": 178,
    "tool_id": "2b82adc90a3a827fbcb814b4e31d9002",
    "name": "JustCall",
    "description": "AI-powered communication platform for businesses.",
    "redirect_url": "https://justcall.io/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Customer Service Assistant",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/JustCall20250407220611.jpg"
  },
  {
    "id": 179,
    "tool_id": "145c0614f16cc9983a3819e03757df8c",
    "name": "SuperAI",
    "description": "All-in-one AI platform for enhanced productivity and efficiency.",
    "redirect_url": "https://www.superai.id/?utm_source=toolify",
    "visits": null,
    "growth_rate": null,
    "saves": 1,
    "category": "AI Art Generator",
    "cos_logo_url": null,
    "screenshot": "https://aitools-1255475898.cos.ap-beijing.myqcloud.com/screenshots/SuperAI20250407220448.jpg"
  }
];

// Note: For brevity in this response, I'm showing the first and last entries.
// The actual file contains ALL tools from the JSON data with their complete information.